---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "manage_key"
      instance_type: t2.micro
      security_group: launch-wizard-1
      region: ap-southeast-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-0f06718ac552afe18", name: "manage-node-1" } # Update AMI ID according 
      - { image: "ami-080660c9757080771", name: "manage-node-2" } # to your account
      - { image: "ami-080660c9757080771", name: "manage-node-3" }